from qkit import *


class S6(CueScene):
    SEG = "s6"

    def construct(self):
        c = chip("When the estimate is wrong")
        p5, p6 = part("5"), part("6")
        stale, fresh = medians("5")[0], medians("6")[0]
        est_stale = est_rows(p5, "Index Scan using orders_s_pkey")
        removed = int(re.search(r"Rows Removed by Filter: (\d+)", p5).group(1))
        est_fresh = est_rows(p6, "Bitmap Heap Scan")
        blocks = re.search(r"Heap Blocks: exact=(\d+)", p6).group(1)

        # 01-04: a snapshot, taken before the data changed
        self.at("01")
        snap = mono("statistics = a snapshot", 22, INK).move_to([0, 2.6, 0])
        self.play(FadeIn(c), FadeIn(snap), run_time=0.6)
        self.at("02")
        cap = mono("orders_s: a copy of orders · autovacuum off, so nothing re-ran ANALYZE after the archiving", 13, MUTED)
        cap.to_edge(DOWN, buff=0.35)
        self.play(FadeIn(cap), run_time=0.4)
        self.at("03")
        then = VGroup(mono("when the statistics were gathered", 14, MUTED), mono("customer 1: ~30% of orders", 20, INK)).arrange(DOWN, buff=0.1)
        then.move_to([-3.4, 1.3, 0])
        self.play(FadeIn(then), run_time=0.5)
        self.at("04")
        now = VGroup(mono("now, after archiving", 14, MUTED), mono("customer 1: 294 orders, all recent", 20, AMBER)).arrange(DOWN, buff=0.1)
        now.move_to([3.4, 1.3, 0])
        self.play(FadeIn(now), run_time=0.5)

        # 05-10: the stale plan walks the order numbers (real run)
        self.at("05")
        q = code_card("SELECT id, amount FROM orders_s WHERE customer_id = 1 ORDER BY id LIMIT 10", 15).move_to([0, 0.1, 0])
        self.play(FadeIn(q), run_time=0.5)
        self.at("06")
        self.play(FadeOut(then), FadeOut(now), FadeOut(snap), q.animate.move_to([0, 2.6, 0]), run_time=0.5)
        believes = mono(f"planner expects {est_stale:,} rows of customer 1", 18, BAD).move_to([0, 1.7, 0])
        self.play(FadeIn(believes), run_time=0.5)
        self.at("07")
        bar = Rectangle(width=10.0, height=0.5, stroke_color=DIM, stroke_width=1.5, fill_color=PANEL, fill_opacity=1).move_to([0, 0.4, 0])
        bl = mono("orders by order number →", 14, MUTED).next_to(bar, UP, 0.1).align_to(bar, LEFT)
        plan = mono("Limit → Index Scan using orders_s_pkey (walks order numbers, checks each row)", 14, INK).next_to(bar, DOWN, 0.2)
        self.play(FadeIn(bar), FadeIn(bl), FadeIn(plan), run_time=0.5)
        exp = mono("expects ten of them almost at once", 14, MUTED).next_to(plan, DOWN, 0.15)
        self.play(FadeIn(exp), run_time=0.4)
        self.at("08")
        tail = Rectangle(width=0.18, height=0.5, stroke_width=0, fill_color=AMBER, fill_opacity=0.9).move_to(bar.get_right(), aligned_edge=RIGHT)
        tl = mono("customer 1's 294 orders", 14, AMBER).next_to(tail, UP, 0.1).align_to(bar, RIGHT)
        self.play(FadeIn(tail), FadeIn(tl), run_time=0.5)
        self.at("09")
        crawl = Rectangle(width=0.01, height=0.5, stroke_width=0, fill_color=BAD, fill_opacity=0.35).move_to(bar.get_left(), aligned_edge=LEFT)
        self.add(crawl)
        self.play(crawl.animate.stretch_to_fit_width(bar.width - 0.18).move_to(bar.get_left(), aligned_edge=LEFT),
                  run_time=1.8, rate_func=linear)
        rr = mono(f"Rows Removed by Filter: {removed:,}", 16, BAD).next_to(exp, DOWN, 0.25)
        self.play(FadeIn(rr), run_time=0.4)
        self.at("10")
        t1 = mono(ms(stale), 24, BAD).next_to(rr, DOWN, 0.25)
        self.play(FadeIn(t1), run_time=0.4)

        # 11-13: ANALYZE, and the right plan (real run)
        self.at("11")
        self.play(*[FadeOut(m) for m in self.mobjects if m not in (c, q, cap)], run_time=0.4)
        an = code_card("ANALYZE orders_s;", 18, ICE).move_to([0, 1.5, 0])
        self.play(FadeIn(an), run_time=0.4)
        exp2 = mono(f"planner now expects {est_fresh} rows (actual 294)", 18, GOOD).next_to(an, DOWN, 0.3)
        self.play(FadeIn(exp2), run_time=0.4)
        self.at("12")
        tr = tree([node("Limit"), node("Sort", "top-N heapsort: keeps the first ten"),
                   node("Bitmap Heap Scan on orders_s", f"Heap Blocks (pages): {blocks}", GOOD),
                   node("Bitmap Index Scan on orders_s_customer_id_idx", "", GOOD, w=5.6)], -4.6, -0.1, gap=0.15, indent=0.4)
        self.play(FadeIn(tr), run_time=0.7)
        self.at("13")
        t2 = VGroup(mono(ms(fresh), 24, GOOD), mono(f"≈ {round(stale / fresh, -2):,.0f}× faster", 18, GOOD)).arrange(DOWN, buff=0.12, aligned_edge=LEFT).move_to([3.4, -1.0, 0], aligned_edge=LEFT)
        self.play(FadeIn(t2), run_time=0.5)

        # 14-16: nobody added an index
        self.at("14")
        self.play(*[FadeOut(m) for m in self.mobjects if m not in (c, cap)], run_time=0.4)
        u = mono("the usual fix: add an index?", 22, MUTED).move_to([0, 1.0, 0])
        self.play(FadeIn(u), run_time=0.4)
        self.at("15")
        ix = mono("orders_s_customer_id_idx: there all along", 20, GOOD).move_to([0, 0.1, 0])
        self.play(FadeIn(ix), run_time=0.4)
        self.at("16")
        dx = mono("the planner just didn't expect it to help", 18, AMBER).move_to([0, -0.7, 0])
        self.play(FadeIn(dx), run_time=0.4)

        # 17-19: reading a slow plan: expected vs actual rows
        self.at("17")
        self.play(FadeOut(u), FadeOut(ix), FadeOut(dx), run_time=0.4)
        head = mono("EXPLAIN ANALYZE", 20, INK).move_to([0, 1.6, 0])
        self.play(FadeIn(head), run_time=0.3)
        self.at("18")
        line = VGroup(mono("Index Scan using orders_s_pkey  (cost=…", 15, INK), mono(f"rows={est_stale}", 15, BAD),
                      mono("…) (actual time=… ", 15, INK), mono("rows=10", 15, BAD), mono("loops=1)", 15, INK)).arrange(RIGHT, buff=0.08)
        line.move_to([0, 0.6, 0])
        self.play(FadeIn(line), run_time=0.5)
        self.play(Create(SurroundingRectangle(line[1], color=BAD, buff=0.06)), Create(SurroundingRectangle(line[3], color=BAD, buff=0.06)), run_time=0.6)
        ev = VGroup(mono("expected", 14, BAD).next_to(line[1], DOWN, 0.2), mono("got", 14, BAD).next_to(line[3], DOWN, 0.2))
        self.play(FadeIn(ev), run_time=0.3)
        self.at("19")
        far = mono("far apart → the plan was chosen for data that isn't there", 18, AMBER).move_to([0, -0.9, 0])
        self.play(FadeIn(far), run_time=0.5)
        self.until(self.dur - 0.5)
        self.play(*[FadeOut(m) for m in self.mobjects], run_time=0.45)
        self.finish()
