from ckit import *


class S5(CueScene):
    SEG = "s5"

    def construct(self):
        c = chip("Channels")
        actor = Actor(1.8, 0.4)
        ma = machine("A", -5.3, 0.4)
        e = envelope("", AMBER).move_to(actor.slot(0))
        self.at("01")
        self.play(FadeIn(c), FadeIn(actor), FadeIn(ma), FadeIn(e), run_time=0.7)
        q = mono("taken yet?", 20, AMBER).next_to(ma, UP, 0.2)
        self.play(FadeIn(q), run_time=0.4)
        self.at("03")
        qq = mono("applied? still queued?", 16, MUTED).next_to(e, RIGHT, 0.2).shift(1.2 * RIGHT + 1.6 * UP)
        self.play(Indicate(e, color=AMBER), run_time=0.6)
        self.at("04")
        cant = mono("the machine can't tell", 18, BAD).move_to([-5.0, -1.2, 0])
        self.play(FadeIn(cant), run_time=0.4)

        # 05-10: CSP channels: a send waits for the receiver
        self.at("05")
        self.play(*[FadeOut(m) for m in self.mobjects if m is not c], run_time=0.4)
        acct = Account(3.6, 0.2, "$100", "account process")
        mb = machine("A", -5.3, 0.2)
        pipe = channel([-4.4, 0.2, 0], [2.3, 0.2, 0])
        pl = mono("channel", 16, MUTED).next_to(pipe, DOWN, 0.25)
        self.play(FadeIn(acct), FadeIn(mb), Create(pipe), FadeIn(pl), run_time=0.8)
        self.at("06")
        csp = mono("CSP (Hoare) → Go channels", 20, INK).move_to([0, 2.6, 0])
        self.play(FadeIn(csp), run_time=0.5)
        self.at("09")
        ev = envelope("50", AMBER).move_to([-3.9, 0.2, 0])
        self.play(FadeIn(ev), run_time=0.3)
        self.play(ev.animate.move_to([-0.8, 0.2, 0]), run_time=0.6)
        wb = waiting_bar(mb.get_bottom() + 0.4 * DOWN + 0.8 * LEFT, 1.6, AMBER, "A waits")
        self.play(FadeIn(wb), run_time=0.4)
        self.play(ev.animate.move_to(acct.box.get_left() + 0.5 * LEFT), run_time=0.6)
        self.at("10")
        self.play(FadeOut(ev), FadeOut(wb), acct.set("$150"), run_time=0.6)
        taken = mono("taken: both move on", 16, GOOD).next_to(mb, DOWN, 0.4)
        self.play(FadeIn(taken), run_time=0.4)
        # 11-12: the account process owns the balance
        self.at("12")
        nd = mono("one owner · no data race", 18, GOOD).next_to(acct, DOWN, 0.4)
        self.play(FadeIn(nd), run_time=0.4)
        # 13-14: Go also allows shared memory
        self.at("13")
        go = mono("Go: goroutines + channels · shared memory also allowed", 17, AMBER).move_to([0, -2.4, 0])
        self.play(FadeIn(go), run_time=0.5)
        self.at("14")
        hab = mono("one owner: a habit (as in Akka)", 16, MUTED).next_to(go, DOWN, 0.12)
        self.play(FadeIn(hab), run_time=0.4)
        # 15-17: side by side
        self.at("15")
        self.play(*[FadeOut(m) for m in self.mobjects if m is not c], run_time=0.4)
        left = VGroup(mono("actor: send, move on", 22, ICE), envelope("", AMBER)).arrange(DOWN, buff=0.4).move_to([-3.2, 0.3, 0])
        right = VGroup(mono("channel: send waits", 22, AMBER), waiting_bar(ORIGIN, 1.6, AMBER, "")).arrange(DOWN, buff=0.4).move_to([3.2, 0.3, 0])
        diff = T("same idea, different plumbing", 30, INK).move_to([0, 2.4, 0])
        self.play(FadeIn(diff), run_time=0.5)
        self.at("16")
        self.play(FadeIn(left), run_time=0.5)
        self.at("17")
        self.play(FadeIn(right), run_time=0.5)
        self.until(self.dur - 0.5)
        self.play(*[FadeOut(m) for m in self.mobjects], run_time=0.45)
        self.finish()
